### DISCUSSION TITLE
Standing Sensor Issue

### DISCUSSION THREAD

**Discussion by medoix** [gcormier/megadesk#175] [Q&A]
Has the standing sensor code broken? I have the following as per the example for the sensor

```
# Custom Standing Desk Sensor
template:
  - binary_sensor:
      - name: "standing"
        state: >
          {{ states('number.megadesk_height_cm')|float > 100 }}
```

But have been getting the following in the HA logs and the status is not being set correctly.

```
ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ states('number.megadesk_height_cm')|float > 100 }}' but no default was specified') while processing template 'Template<template=({{ states('number.megadesk_height_cm')|float > 100 }}) renders=4>' for attribute '_state' in entity 'binary_sensor.standing'
```
