### ISSUE TITLE
Right Buttons not working anymore via HA (companion)

### ISSUE THREAD

**Issue by webmediart-github** [gcormier/megadesk#184]
Hi there,

first of all, thank you very much for the hardware and overall product! It is a blessing to have some memory retro-fitted.

As described here https://github.com/gcormier/megadesk/discussions/158 I managed to get the buttons working by adding the buttons and enabling two button mode.
Since I updated the configuration with the latest update (as I understood removing some outdated stuff which is not supported anymore), the memory slots of the right button are only accessible via the physical buttons, but not through the entities setup for homeassistant.

Here is my configuration file:
```
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: recommended

esphome:
  name: megadesk
  comment: megadesk-companion
  platformio_options:
    board_build.flash_mode: dio # If you don't specify this using esp-idf framework, the device will boot-loop.

uart:
  id: uart_desk
  baud_rate: 115200
  tx_pin: GPIO6
  rx_pin: GPIO7

logger:
  hardware_uart: USB_SERIAL_JTAG # Logging over the USB-C port (WiFi will always log as well)

external_components:
   - source: github://gcormier/megadesk_companion/esphome@main
     components: [ megadesk ]
     refresh: 120s

api:
  encryption:
    key: "XXX"

ota:
  - platform: esphome
    password: "XXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Companion Fallback"
    password: "megadesk"

captive_portal:

web_server:
  port: 80

sensor:
  - platform: megadesk
    max_height:
      name: "Max Height"
    min_height:
      name: "Min Height"
    raw_height:
      name: "Raw Height"
      id: megadesk_raw
      on_value:
        then:
          - component.update: megadesk_height_inches
          - component.update: megadesk_height_cm
          - component.update: megadesk_height_raw
    height_cm:
      name: "Height (cm)"
    height_inches:
      name: "Height (in)"

number:
  - platform: template
    name: "Megadesk Height (inches)"
    id: megadesk_height_inches
    internal: true
    min_value: 23
    max_value: 47
    step: 0.53
    mode: slider
    update_interval: never
    unit_of_measurement: 'inches'
    lambda: |-
      return ((((id(megadesk_raw).state - 299) * (47 - 23)) / (6914 - 299)) + 23);
    set_action:
      - number.set:
          id: megadesk_height_raw
          value: !lambda "return int((((x - 23) * (6914 - 299)) / (47 - 23)) + 299);"
  - platform: template
    name: "Megadesk Height (cm)"
    id: megadesk_height_cm
    min_value: 58.42
    max_value: 118.745
    step: 0.53
    mode: slider
    update_interval: never
    unit_of_measurement: 'cm'
    lambda: |-
      return ((((id(megadesk_raw).state - 299) * (119.38 - 58.42)) / (6914 - 299)) + 58.42);
    set_action:
      - number.set:
          id: megadesk_height_raw
          value: !lambda "return int((((x - 58.42) * (6640 - 299)) / (119.38 - 58.42)) + 299);"
  - platform: template
    name: "Megadesk Height (raw)"
    id: megadesk_height_raw
    min_value: 299
    max_value: 6640
    step: 1
    mode: slider
    update_interval: never
    lambda: |-
      return id(megadesk_raw).state;
    set_action:
      - uart.write: !lambda |-
          char buf[20];
          sprintf(buf, "<=%i,.", int(x));
          std::string s = buf;
          return std::vector<unsigned char>( s.begin(), s.end() );

button:
  - platform: template
    name: "Desk Position 2 (UP)"
    on_press:
      then:
        - uart.write: "<L0,2."
  - platform: template
    name: "Desk Position 3 (UP)"
    on_press:
      then:
        - uart.write: "<L0,3."
  - platform: template
    name: "Desk Position 2 (DOWN)"
    on_press:
      then:
        - uart.write: "<R0,2."
  - platform: template
    name: "Desk Position 3 (DOWN)"
    on_press:
      then:
        - uart.write: "<R0,3."
  - platform: template
    name: "Toggle Minimum Desk Height"
    on_press:
      then:
        - uart.write: "<L0,11."
        - uart.write: "<R0,11."
  - platform: template
    name: "Toggle Maximum Desk Height"
    on_press:
      then:
        - uart.write: "<L0,12."
        - uart.write: "<R0,12."
  - platform: template
    name: "Recalibrate Desk"
    on_press:
      then:
        - uart.write: "<L0,14."
  - platform: template
    name: "Reboot Megadesk"
    on_press:
      then:
        - uart.write: "<L0,15."
  - platform: template
    name: "Toggle Audio feedback"
    on_press:
      then:
        - uart.write: "<L0,17."
  - platform: template
    name: "Toggle both-button mode"
    on_press:
      then:
        - uart.write: "<L0,18."

interval:
  - interval: 300s
    then:
      - uart.write: "<C0.0."
```

In the web-ui any button press is registered/logged as such, e.g.
```
00:19:20 | [D] | [button:010] | 'Desk Position 3 (DOWN)' Pressed.
00:19:28 | [D] | [button:010] | 'Desk Position 2 (DOWN)' Pressed.
```
But nothing happens.

I also noticed, that in some instances, where I power-cycled the device, it worked at first but stopped working after some time.
